import './nala-mobile.css';
import type { Metadata } from 'next';
import { ArrowRight, BadgeCheck, BatteryCharging, CircleCheck, Headphones, MapPin, MessageCircle, RefreshCw, ShieldCheck, Smartphone, Sparkles, Truck } from 'lucide-react';

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL ?? 'https://studio.naltech.web.id';
const whatsappUrl = 'https://wa.me/6281573550017?text=Halo%20Nala%20Mobile%2C%20saya%20ingin%20konsultasi%20tentang%20smartphone.';

export const metadata: Metadata = { title: 'Nala Mobile — Showroom Smartphone Terpercaya', description: 'Temukan smartphone pilihan, layanan trade-in, dan pengalaman belanja yang lebih nyaman di Nala Mobile.', alternates: { canonical: '/demo/nala-mobile' }, openGraph: { title: 'Nala Mobile — Upgrade yang terasa tepat', description: 'Showroom smartphone dengan pilihan terkurasi, harga transparan, dan konsultasi personal.', url: `${siteUrl}/demo/nala-mobile`, images: [{ url: `${siteUrl}/mobile-showroom/hero-phones.png`, width: 1536, height: 1024, alt: 'Tiga smartphone di showroom Nala Mobile' }] }, twitter: { card: 'summary_large_image', title: 'Nala Mobile — Upgrade yang terasa tepat', description: 'Showroom smartphone dengan pilihan terkurasi dan layanan trade-in.', images: [`${siteUrl}/mobile-showroom/hero-phones.png`] } };

const products = [
  { name: 'Nala Pro 16', type: 'Flagship performance', price: 'Mulai Rp 12,9 jt', tone: 'blue', mark: 'PRO' },
  { name: 'Nala Air 8', type: 'Tipis, ringan, all-day', price: 'Mulai Rp 7,4 jt', tone: 'silver', mark: 'AIR' },
  { name: 'Nala Core 5G', type: 'Power untuk setiap hari', price: 'Mulai Rp 4,8 jt', tone: 'coral', mark: 'CORE' },
];
const benefits = [
  { icon: BadgeCheck, title: 'Unit resmi & bergaransi', text: 'Semua perangkat dipilih dari distributor resmi dengan garansi yang jelas.' },
  { icon: RefreshCw, title: 'Trade-in lebih mudah', text: 'Bawa perangkat lama dan dapatkan estimasi harga secara transparan.' },
  { icon: Headphones, title: 'Dibantu sampai paham', text: 'Konsultasi personal untuk menemukan perangkat yang sesuai kebutuhan.' },
];

export default function NalaMobilePage() {
  return <main className="nm-page" id="top">
    <div className="nm-announcement"><span>SHOWROOM BARU DI JAKARTA</span><a href="#visit">Atur kunjungan <ArrowRight size={14} /></a></div>
    <nav className="nm-nav" aria-label="Navigasi Nala Mobile"><a className="nm-logo" href="#top"><span>N</span><strong>NALA<span>MOBILE</span></strong></a><div className="nm-nav-links"><a href="#collection">Koleksi</a><a href="#trade-in">Trade-in</a><a href="#experience">Layanan</a><a href="#visit">Showroom</a></div><a className="nm-nav-cta" href={whatsappUrl} target="_blank" rel="noreferrer">Konsultasi <ArrowRight size={15} /></a></nav>
    <section className="nm-hero"><div className="nm-hero-copy"><p className="nm-eyebrow"><span /> Smart choice, better everyday</p><h1>Upgrade yang<br /><em>terasa tepat.</em></h1><p className="nm-lead">Temukan smartphone yang bukan hanya terlihat bagus, tapi benar-benar cocok dengan cara kamu bekerja, berkarya, dan menikmati hari.</p><div className="nm-actions"><a className="nm-button" href="#collection">Lihat koleksi <ArrowRight size={17} /></a><a className="nm-text-link" href={whatsappUrl} target="_blank" rel="noreferrer">Tanya advisor <MessageCircle size={16} /></a></div><div className="nm-proof"><span><CircleCheck size={15} /> Unit resmi</span><span><CircleCheck size={15} /> Bisa trade-in</span><span><CircleCheck size={15} /> Cicilan tersedia</span></div></div><div className="nm-hero-visual"><img src="/mobile-showroom/hero-phones.png" alt="Tiga smartphone premium di Nala Mobile" /><div className="nm-float-card nm-float-top"><Sparkles size={17} /><span>Curated picks<small>pilihan minggu ini</small></span></div><div className="nm-float-card nm-float-bottom"><BatteryCharging size={19} /><span>All-day ready<small>daya tahan untuk aktivitasmu</small></span></div></div></section>
    <section className="nm-marquee" aria-label="Kategori produk"><div><span>SMARTPHONE</span><i>✦</i><span>TABLET</span><i>✦</i><span>AUDIO</span><i>✦</i><span>ACCESSORIES</span><i>✦</i><span>SMARTPHONE</span><i>✦</i><span>TABLET</span></div></section>
    <section className="nm-collection" id="collection"><div className="nm-section-head"><div><p className="nm-eyebrow"><span /> Yang sedang dicari</p><h2>Pilihan untuk<br /><em>setiap gaya.</em></h2></div><p>Bukan sekadar banyak pilihan. Kami memilihkan perangkat dengan performa, desain, dan harga yang masuk akal untuk kebutuhanmu.</p></div><div className="nm-product-grid">{products.map((product, index) => <article className={`nm-product nm-product-${product.tone}`} key={product.name}><div className="nm-product-top"><span>0{index + 1}</span><a href={whatsappUrl} target="_blank" rel="noreferrer" aria-label={`Tanya tentang ${product.name}`}><ArrowRight size={18} /></a></div><div className="nm-device"><div className="nm-device-screen"><small>{product.mark}</small><strong>{index === 0 ? '16' : index === 1 ? '08' : '05'}</strong></div></div><div className="nm-product-info"><div><p>{product.type}</p><h3>{product.name}</h3></div><strong>{product.price}</strong></div></article>)}</div><a className="nm-outline-link" href={whatsappUrl} target="_blank" rel="noreferrer">Tanya stok & warna yang tersedia <ArrowRight size={17} /></a></section>
    <section className="nm-trade" id="trade-in"><div className="nm-trade-copy"><p className="nm-eyebrow"><span /> Upgrade tanpa drama</p><h2>Perangkat lama<br />punya <em>nilai baru.</em></h2><p>Jadikan smartphone lama sebagai bagian dari upgrade berikutnya. Tim kami bantu cek kondisi, memberi estimasi, lalu potong langsung dari pembelianmu.</p><a className="nm-dark-button" href={whatsappUrl} target="_blank" rel="noreferrer">Cek estimasi trade-in <ArrowRight size={17} /></a></div><div className="nm-trade-card"><div className="nm-trade-icon"><RefreshCw size={28} /></div><span>TRADE-IN PROGRAM</span><strong>Lebih ringan<br />untuk upgrade.</strong><div className="nm-trade-steps"><span><b>01</b> Cek kondisi</span><span><b>02</b> Dapat estimasi</span><span><b>03</b> Pilih perangkat baru</span></div></div></section>
    <section className="nm-experience" id="experience"><div className="nm-section-head nm-section-head-light"><div><p className="nm-eyebrow"><span /> Nala experience</p><h2>Belanja dengan<br /><em>lebih tenang.</em></h2></div><p>Datang untuk mencoba langsung, pulang dengan pilihan yang benar-benar kamu mengerti.</p></div><div className="nm-benefit-grid">{benefits.map(({ icon: Icon, title, text }) => <article key={title}><span className="nm-benefit-icon"><Icon size={22} /></span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section className="nm-visit" id="visit"><div className="nm-visit-card"><div><p className="nm-eyebrow"><span /> Berkunjung</p><h2>Rasakan langsung<br /><em>bedanya.</em></h2><p>Datang ke showroom kami untuk mencoba perangkat, membandingkan pilihan, dan berkonsultasi tanpa terburu-buru.</p><a className="nm-dark-button" href={whatsappUrl} target="_blank" rel="noreferrer">Atur kunjungan <ArrowRight size={17} /></a></div><div className="nm-location"><MapPin size={22} /><span>Showroom Nala Mobile<small>Jl. Senopati Raya No. 18<br />Jakarta Selatan · 10.00—21.00</small></span></div></div></section>
    <footer className="nm-footer"><a className="nm-logo" href="#top"><span>N</span><strong>NALA<span>MOBILE</span></strong></a><p>Smartphone, dipilih dengan lebih personal.</p><div><a href="#collection">Koleksi</a><a href="#trade-in">Trade-in</a><a href={whatsappUrl} target="_blank" rel="noreferrer">WhatsApp ↗</a></div><small>Concept website independently created by Naltech Studio.</small></footer>
  </main>;
}
